version: '3.9'
services:
  tailscale:
    container_name: tailscale
    hostname: shared
    image: tailscale/tailscale
    stdin_open: true
    environment:
      - TS_AUTHKEY
      - TS_USERSPACE=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    volumes:
      - varlib:/var/lib
  nginx:
    container_name: nginx-tailscale
    image: public.ecr.aws/nginx/nginx:1.23
    stdin_open: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    network_mode: 'service:tailscale'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './nginx/shared.conf:/etc/nginx/conf.d/shared.conf:ro'
      - './:/usr/share/nginx/html/:ro'
      - varlib:/var/lib
    restart: unless-stopped
volumes:
  varlib:
